/**
 * Shared industry list used across founder profile, investor filter, and provider filter.
 * Covers the full startup ecosystem.
 */
export const INDUSTRIES = [
  'Adtech',
  'Agritech',
  'AI / Machine Learning',
  'AR / VR / XR',
  'Automotive',
  'Biotech',
  'Blockchain / Web3',
  'Cleantech / Sustainability',
  'Cloudtech / SaaS',
  'Construction / Proptech',
  'Consumer Goods',
  'Creator Economy',
  'Cybersecurity',
  'Deep Tech',
  'E-commerce / Retail',
  'Edtech',
  'Energy',
  'Entertainment',
  'Fashion / Apparel',
  'Fintech',
  'Foodtech',
  'Gaming',
  'General',
  'GovTech',
  'Hardware / IoT',
  'Healthcare / Medtech',
  'HRtech / Future of Work',
  'Insurtech',
  'Legal Tech',
  'Logistics / Supply Chain',
  'Manufacturing',
  'Marketplace',
  'Media',
  'Mobility / Transportation',
  'No-code / Low-code',
  'Pettech',
  'Real Estate',
  'Robotics',
  'Social Impact',
  'Social Media',
  'Space Tech',
  'Sports Tech',
  'Technology',
  'Travel / Hospitality',
  'Wellness / Fitness',
];
