/**
 * mockData.js — India-first fallback opportunities across ALL sectors.
 * Shown when APIs fail or are slow. Covers tech, healthcare, government,
 * agriculture, engineering, education, and finance.
 */

export const MOCK_OPPORTUNITIES = [
  // ── Tech ──────────────────────────────────────────────────────────────────
  {
    id: 'mock_1', sourceId: 'mock_1', sourceName: 'Demo', sourceUrl: '#',
    title: 'React Frontend Developer',
    companyName: 'TechCorp India', companyLogo: null,
    description: 'Build modern web apps using React, TypeScript, and Tailwind for our Bangalore-based product team. Work remotely or from our HSR Layout office.',
    shortDescription: 'Build web apps using React and TypeScript. Bangalore/Remote.',
    skills: ['React', 'TypeScript', 'Tailwind CSS'],
    category: 'Web Development', opportunityType: 'Freelance', workMode: 'Remote',
    experienceLevel: 'Intermediate', location: 'Bangalore, India', country: 'IN', city: 'Bangalore',
    budgetMin: 50000, budgetMax: 80000, currency: 'INR', stipend: null,
    duration: '3 months', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: true,
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    tags: ['React', 'India', 'Remote'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_2', sourceId: 'mock_2', sourceName: 'Demo', sourceUrl: '#',
    title: 'Flutter Mobile Developer',
    companyName: 'AppVenture Noida', companyLogo: null,
    description: 'Build cross-platform mobile apps for Indian consumers. Fintech and edtech products for Bharat users. Noida office, hybrid work.',
    shortDescription: 'Build mobile apps for Indian fintech and edtech. Noida/Hybrid.',
    skills: ['Flutter', 'Dart', 'Firebase'],
    category: 'Mobile Development', opportunityType: 'Full-time', workMode: 'Hybrid',
    experienceLevel: 'Intermediate', location: 'Noida, India', country: 'IN', city: 'Noida',
    budgetMin: 60000, budgetMax: 100000, currency: 'INR', stipend: null,
    duration: 'Permanent', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    tags: ['Flutter', 'Noida', 'Fintech'], isSaved: false, isApplied: false, raw: {},
  },

  // ── Healthcare ────────────────────────────────────────────────────────────
  {
    id: 'mock_3', sourceId: 'mock_3', sourceName: 'Demo', sourceUrl: '#',
    title: 'Staff Nurse — General Ward',
    companyName: 'Apollo Hospitals', companyLogo: null,
    description: 'Apollo Hospitals Chennai is hiring BSc Nursing / GNM qualified staff nurses for the general ward. Competitive salary and accommodation provided.',
    shortDescription: 'BSc Nursing / GNM staff nurse opening at Apollo Hospitals Chennai.',
    skills: ['Nursing', 'Patient Care', 'IV Administration', 'GNM'],
    category: 'Healthcare', opportunityType: 'Full-time', workMode: 'On-site',
    experienceLevel: 'Beginner', location: 'Chennai, India', country: 'IN', city: 'Chennai',
    budgetMin: 25000, budgetMax: 35000, currency: 'INR', stipend: null,
    duration: 'Permanent', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: true,
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    tags: ['Nursing', 'Chennai', 'Healthcare', 'Apollo'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_4', sourceId: 'mock_4', sourceName: 'Demo', sourceUrl: '#',
    title: 'MBBS Doctor — General Physician',
    companyName: 'Fortis Healthcare', companyLogo: null,
    description: 'Fortis Gurugram is hiring MBBS / MD general physicians for OPD and IPD management. Fresh MBBS welcome to apply.',
    shortDescription: 'MBBS / MD general physician opening at Fortis Gurugram.',
    skills: ['MBBS', 'OPD Management', 'Clinical Diagnosis'],
    category: 'Healthcare', opportunityType: 'Full-time', workMode: 'On-site',
    experienceLevel: 'Beginner', location: 'Gurugram, India', country: 'IN', city: 'Gurugram',
    budgetMin: 60000, budgetMax: 120000, currency: 'INR', stipend: null,
    duration: 'Permanent', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    tags: ['Doctor', 'MBBS', 'Gurugram', 'Healthcare'], isSaved: false, isApplied: false, raw: {},
  },

  // ── Government ────────────────────────────────────────────────────────────
  {
    id: 'mock_5', sourceId: 'mock_5', sourceName: 'Employment News', sourceUrl: '#',
    title: 'SSC CGL 2025 — Combined Graduate Level Examination',
    companyName: 'Staff Selection Commission', companyLogo: null,
    description: 'SSC CGL 2025 notification released. Posts: Inspector (Income Tax), Assistant Audit Officer, Junior Statistical Officer. Graduates from any stream can apply. Age: 18–32 years.',
    shortDescription: 'SSC CGL 2025 — graduate level posts across central government departments.',
    skills: ['General Aptitude', 'Reasoning', 'English', 'Mathematics'],
    category: 'Government', opportunityType: 'Full-time', workMode: 'On-site',
    experienceLevel: 'Beginner', location: 'India (All India)', country: 'IN', city: '',
    sector: 'Government',
    budgetMin: 25000, budgetMax: 75000, currency: 'INR', stipend: null,
    duration: 'Permanent', applyType: 'external', applyUrl: 'https://ssc.gov.in',
    isVerified: true, isUrgent: true,
    postedAt: new Date(Date.now() - 0.5 * 86400000).toISOString(),
    tags: ['SSC', 'CGL', 'Government', 'India'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_6', sourceId: 'mock_6', sourceName: 'Employment News', sourceUrl: '#',
    title: 'UPSC Civil Services 2025 — IAS / IPS / IFS',
    companyName: 'Union Public Service Commission', companyLogo: null,
    description: 'UPSC CSE 2025 notification. Eligibility: Any degree. Age: 21–32 (relaxation for OBC/SC/ST). Apply on upsc.gov.in. Prelims, Mains, and Interview stages.',
    shortDescription: 'UPSC Civil Services 2025 — IAS, IPS, IFS and other All India Services.',
    skills: ['General Studies', 'Essay', 'Optional Subject', 'Current Affairs'],
    category: 'Government', opportunityType: 'Full-time', workMode: 'On-site',
    experienceLevel: 'Intermediate', location: 'India (All India)', country: 'IN', city: '',
    sector: 'Government',
    budgetMin: 56000, budgetMax: 250000, currency: 'INR', stipend: null,
    duration: 'Permanent', applyType: 'external', applyUrl: 'https://upsc.gov.in',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    tags: ['UPSC', 'IAS', 'IPS', 'Government', 'India'], isSaved: false, isApplied: false, raw: {},
  },

  // ── Agriculture ───────────────────────────────────────────────────────────
  {
    id: 'mock_7', sourceId: 'mock_7', sourceName: 'Demo', sourceUrl: '#',
    title: 'Agricultural Officer — Crop Science',
    companyName: 'ICAR — Indian Council of Agricultural Research', companyLogo: null,
    description: 'ICAR is hiring Agricultural Officers (BSc Agriculture / MSc Agronomy) for field research stations across India. Research in crop improvement and soil health.',
    shortDescription: 'BSc / MSc Agriculture opening at ICAR for crop science research.',
    skills: ['Crop Science', 'Soil Health', 'Agronomy', 'Research'],
    category: 'Agriculture', opportunityType: 'Full-time', workMode: 'On-site',
    experienceLevel: 'Beginner', location: 'New Delhi, India', country: 'IN', city: 'New Delhi',
    budgetMin: 35000, budgetMax: 56000, currency: 'INR', stipend: null,
    duration: 'Permanent', applyType: 'external', applyUrl: 'https://icar.org.in',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    tags: ['Agriculture', 'ICAR', 'India', 'Research'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_8', sourceId: 'mock_8', sourceName: 'Demo', sourceUrl: '#',
    title: 'Horticulture Development Officer',
    companyName: 'Maharashtra State Horticulture Mission', companyLogo: null,
    description: 'Horticulture graduates required for field extension work in rural Maharashtra. Drive adoption of modern horticulture practices among farmers.',
    shortDescription: 'Horticulture graduate opening — field extension work in Maharashtra.',
    skills: ['Horticulture', 'Extension Work', 'Farmer Training'],
    category: 'Agriculture', opportunityType: 'Full-time', workMode: 'On-site',
    experienceLevel: 'Beginner', location: 'Pune, India', country: 'IN', city: 'Pune',
    budgetMin: 28000, budgetMax: 40000, currency: 'INR', stipend: null,
    duration: 'Permanent', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    tags: ['Horticulture', 'Maharashtra', 'Agriculture'], isSaved: false, isApplied: false, raw: {},
  },

  // ── Engineering ───────────────────────────────────────────────────────────
  {
    id: 'mock_9', sourceId: 'mock_9', sourceName: 'Demo', sourceUrl: '#',
    title: 'Civil Engineer — Infrastructure Projects',
    companyName: 'L&T Construction', companyLogo: null,
    description: 'L&T Infrastructure Division is hiring BE/BTech Civil Engineers for highway and bridge projects across India. Site-based roles with excellent growth prospects.',
    shortDescription: 'BE/BTech Civil Engineer for highway projects at L&T India.',
    skills: ['AutoCAD', 'Civil Design', 'Site Supervision', 'MS Project'],
    category: 'Engineering', opportunityType: 'Full-time', workMode: 'On-site',
    experienceLevel: 'Beginner', location: 'Mumbai, India', country: 'IN', city: 'Mumbai',
    budgetMin: 45000, budgetMax: 70000, currency: 'INR', stipend: null,
    duration: 'Permanent', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    tags: ['Civil', 'L&T', 'Engineering', 'Mumbai'], isSaved: false, isApplied: false, raw: {},
  },

  // ── Education ─────────────────────────────────────────────────────────────
  {
    id: 'mock_10', sourceId: 'mock_10', sourceName: 'Demo', sourceUrl: '#',
    title: 'Assistant Professor — Computer Science',
    companyName: 'VIT University', companyLogo: null,
    description: 'VIT Vellore is hiring Assistant Professors in Computer Science / IT. PhD preferred, ME/MTech with distinction considered. Teaching + research responsibilities.',
    shortDescription: 'Assistant Professor — CS/IT at VIT Vellore. PhD/MTech eligible.',
    skills: ['Teaching', 'Research', 'Computer Science', 'Python'],
    category: 'Education', opportunityType: 'Full-time', workMode: 'On-site',
    experienceLevel: 'Expert', location: 'Vellore, India', country: 'IN', city: 'Vellore',
    budgetMin: 60000, budgetMax: 100000, currency: 'INR', stipend: null,
    duration: 'Permanent', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    tags: ['Teaching', 'VIT', 'Education', 'Professor'], isSaved: false, isApplied: false, raw: {},
  },

  // ── Finance ───────────────────────────────────────────────────────────────
  {
    id: 'mock_11', sourceId: 'mock_11', sourceName: 'Demo', sourceUrl: '#',
    title: 'Chartered Accountant — Tax & Audit',
    companyName: 'Deloitte India', companyLogo: null,
    description: 'Deloitte Hyderabad is hiring newly qualified CAs for tax compliance and audit practice. Excellent exposure to MNC clients and fast career progression.',
    shortDescription: 'Newly qualified CA opening at Deloitte Hyderabad — tax & audit.',
    skills: ['CA', 'Taxation', 'Audit', 'GST', 'Direct Tax'],
    category: 'Finance', opportunityType: 'Full-time', workMode: 'Hybrid',
    experienceLevel: 'Beginner', location: 'Hyderabad, India', country: 'IN', city: 'Hyderabad',
    budgetMin: 70000, budgetMax: 100000, currency: 'INR', stipend: null,
    duration: 'Permanent', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    tags: ['CA', 'Finance', 'Deloitte', 'Hyderabad'], isSaved: false, isApplied: false, raw: {},
  },
];
