/**
 * mockData.js — India-first fallback opportunities shown when all APIs fail.
 * All listings are India-based or remote-eligible for Indian candidates.
 */

export const MOCK_OPPORTUNITIES = [
  {
    id: 'mock_1', sourceId: 'mock_1', sourceName: 'Demo', sourceUrl: '#',
    title: 'React Frontend Developer',
    companyName: 'TechCorp India', companyLogo: null,
    description: 'We are looking for a skilled React developer to join our Bangalore office or work fully remote from India. You will build modern web apps using React, TypeScript, and Tailwind.',
    shortDescription: 'Build modern web apps using React, TypeScript, and Tailwind. India/Remote.',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'REST APIs'],
    category: 'Web Development', opportunityType: 'Freelance', workMode: 'Remote',
    experienceLevel: 'Intermediate', location: 'Bangalore, India', country: 'IN', city: 'Bangalore',
    budgetMin: 50000, budgetMax: 80000, stipend: null, currency: 'INR',
    duration: '3 months', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: true,
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    deadline: null, employerRating: 4.5,
    tags: ['React', 'India', 'Remote', 'Freelance'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_2', sourceId: 'mock_2', sourceName: 'Demo', sourceUrl: '#',
    title: 'UI/UX Designer (Internship)',
    companyName: 'DesignStudio Pune', companyLogo: null,
    description: 'Join our Pune-based design team as an intern. Work on real projects for Indian startups, learn Figma, and ship features used by thousands.',
    shortDescription: 'Intern with a Pune-based studio — ship real features for Indian startups.',
    skills: ['Figma', 'UI Design', 'Prototyping', 'User Research'],
    category: 'UI/UX', opportunityType: 'Internship', workMode: 'Hybrid',
    experienceLevel: 'Beginner', location: 'Pune, India', country: 'IN', city: 'Pune',
    budgetMin: null, budgetMax: null, stipend: 15000, currency: 'INR',
    duration: '6 months', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    deadline: null, employerRating: 4.2,
    tags: ['Figma', 'Intern', 'Pune', 'Design'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_3', sourceId: 'mock_3', sourceName: 'Demo', sourceUrl: '#',
    title: 'Node.js Backend Engineer',
    companyName: 'CloudBase', companyLogo: null,
    description: 'Fully remote contract role open to India candidates. Build scalable APIs, integrate third-party services, and mentor junior devs. Experience with Node.js, MongoDB, AWS required.',
    shortDescription: 'Remote contract — build scalable Node.js APIs. Open to India.',
    skills: ['Node.js', 'Express', 'MongoDB', 'AWS'],
    category: 'Web Development', opportunityType: 'Contract', workMode: 'Remote',
    experienceLevel: 'Expert', location: 'Remote (India)', country: 'IN', city: '',
    budgetMin: 80000, budgetMax: 120000, stipend: null, currency: 'INR',
    duration: '4 months', applyType: 'external', applyUrl: '#',
    isVerified: false, isUrgent: true,
    postedAt: new Date(Date.now() - 0.5 * 86400000).toISOString(),
    deadline: null, employerRating: 3.9,
    tags: ['Node.js', 'Contract', 'Remote', 'India'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_4', sourceId: 'mock_4', sourceName: 'Demo', sourceUrl: '#',
    title: 'Content Writer — Tech & SaaS',
    companyName: 'ContentHive Mumbai', companyLogo: null,
    description: 'Write long-form blog posts, case studies, and landing page copy for Indian tech startups. SEO knowledge preferred. Work from Mumbai or fully remote.',
    shortDescription: 'Write content for Indian tech startups. Mumbai/Remote.',
    skills: ['Content Writing', 'SEO', 'Copywriting'],
    category: 'Content Writing', opportunityType: 'Part-time', workMode: 'Remote',
    experienceLevel: 'Beginner', location: 'Mumbai, India', country: 'IN', city: 'Mumbai',
    budgetMin: 10000, budgetMax: 25000, stipend: null, currency: 'INR',
    duration: 'Ongoing', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    deadline: null, employerRating: 4.0,
    tags: ['Writing', 'Mumbai', 'Remote', 'Part-time'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_5', sourceId: 'mock_5', sourceName: 'Demo', sourceUrl: '#',
    title: 'Data Analyst — Python & SQL',
    companyName: 'DataWave Hyderabad', companyLogo: null,
    description: 'Analyze large datasets for Indian e-commerce and fintech clients. Build dashboards, deliver weekly reports. Hyderabad office or remote from anywhere in India.',
    shortDescription: 'Analyze datasets for Indian clients. Hyderabad/Remote.',
    skills: ['Python', 'SQL', 'Pandas', 'Tableau'],
    category: 'Data', opportunityType: 'Freelance', workMode: 'Remote',
    experienceLevel: 'Intermediate', location: 'Hyderabad, India', country: 'IN', city: 'Hyderabad',
    budgetMin: 35000, budgetMax: 70000, stipend: null, currency: 'INR',
    duration: '2 months', applyType: 'external', applyUrl: '#',
    isVerified: false, isUrgent: false,
    postedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    deadline: null, employerRating: 4.3,
    tags: ['Python', 'SQL', 'Hyderabad', 'Data'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_6', sourceId: 'mock_6', sourceName: 'Demo', sourceUrl: '#',
    title: 'Flutter Mobile Developer',
    companyName: 'AppVenture', companyLogo: null,
    description: 'Build cross-platform mobile apps for Indian consumers. Noida office, flexible remote. Collaborate with a team building fintech and edtech products for Bharat.',
    shortDescription: 'Build mobile apps for Indian consumers. Noida/Remote.',
    skills: ['Flutter', 'Dart', 'Firebase', 'REST APIs'],
    category: 'Mobile Development', opportunityType: 'Full-time', workMode: 'Hybrid',
    experienceLevel: 'Intermediate', location: 'Noida, India', country: 'IN', city: 'Noida',
    budgetMin: 60000, budgetMax: 100000, stipend: null, currency: 'INR',
    duration: 'Permanent', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    deadline: null, employerRating: 4.6,
    tags: ['Flutter', 'Noida', 'Fintech', 'Edtech'], isSaved: false, isApplied: false, raw: {},
  },
];
