/**
 * mockData.js — Fallback opportunities shown when all APIs fail or are slow.
 * Also used in development when network calls are blocked by CORS.
 */

export const MOCK_OPPORTUNITIES = [
  {
    id: 'mock_1', sourceId: 'mock_1', sourceName: 'Demo', sourceUrl: '#',
    title: 'React Frontend Developer',
    companyName: 'TechCorp', companyLogo: null,
    description: 'We are looking for a skilled React developer to join our remote team. You will build modern web apps using React, TypeScript, and Tailwind.',
    shortDescription: 'Build modern web apps using React, TypeScript, and Tailwind.',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'REST APIs'],
    category: 'Web Development', opportunityType: 'Freelance', workMode: 'Remote',
    experienceLevel: 'Intermediate', location: 'Remote', country: 'IN', city: '',
    budgetMin: 50000, budgetMax: 80000, stipend: null, currency: 'INR',
    duration: '3 months', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: true,
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    deadline: null, employerRating: 4.5,
    tags: ['React', 'Remote', 'Freelance'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_2', sourceId: 'mock_2', sourceName: 'Demo', sourceUrl: '#',
    title: 'UI/UX Designer (Internship)',
    companyName: 'DesignStudio', companyLogo: null,
    description: 'Join our design team as an intern. Work on real projects, learn Figma, and ship features used by thousands.',
    shortDescription: 'Join our design team as an intern and ship real features.',
    skills: ['Figma', 'UI Design', 'Prototyping', 'User Research'],
    category: 'UI/UX', opportunityType: 'Internship', workMode: 'Remote',
    experienceLevel: 'Beginner', location: 'Remote', country: 'IN', city: '',
    budgetMin: null, budgetMax: null, stipend: 15000, currency: 'INR',
    duration: '6 months', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    deadline: null, employerRating: 4.2,
    tags: ['Figma', 'Intern', 'Design'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_3', sourceId: 'mock_3', sourceName: 'Demo', sourceUrl: '#',
    title: 'Node.js Backend Engineer',
    companyName: 'CloudBase', companyLogo: null,
    description: 'Contract role for an experienced Node.js developer. Build scalable APIs, integrate third-party services, and mentor junior devs.',
    shortDescription: 'Contract role — build scalable Node.js APIs and integrations.',
    skills: ['Node.js', 'Express', 'MongoDB', 'AWS'],
    category: 'Web Development', opportunityType: 'Contract', workMode: 'Remote',
    experienceLevel: 'Expert', location: 'Remote', country: 'US', city: '',
    budgetMin: 80, budgetMax: 120, stipend: null, currency: 'USD',
    duration: '4 months', applyType: 'external', applyUrl: '#',
    isVerified: false, isUrgent: true,
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    deadline: null, employerRating: 3.9,
    tags: ['Node.js', 'Contract', 'Remote', 'Expert'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_4', sourceId: 'mock_4', sourceName: 'Demo', sourceUrl: '#',
    title: 'Content Writer — Tech & SaaS',
    companyName: 'ContentHive', companyLogo: null,
    description: 'Write long-form blog posts, case studies, and landing page copy for tech startups. SEO knowledge is a plus.',
    shortDescription: 'Write blog posts and landing copy for tech startups.',
    skills: ['Content Writing', 'SEO', 'Copywriting'],
    category: 'Content Writing', opportunityType: 'Part-time', workMode: 'Remote',
    experienceLevel: 'Beginner', location: 'Remote', country: 'IN', city: '',
    budgetMin: 10000, budgetMax: 25000, stipend: null, currency: 'INR',
    duration: 'Ongoing', applyType: 'external', applyUrl: '#',
    isVerified: true, isUrgent: false,
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    deadline: null, employerRating: 4.0,
    tags: ['Writing', 'Remote', 'Part-time'], isSaved: false, isApplied: false, raw: {},
  },
  {
    id: 'mock_5', sourceId: 'mock_5', sourceName: 'Demo', sourceUrl: '#',
    title: 'Data Analyst — Python & SQL',
    companyName: 'DataWave', companyLogo: null,
    description: 'Analyze large datasets, build dashboards, and deliver weekly reports. Experience with Python, SQL, and Tableau preferred.',
    shortDescription: 'Analyze datasets and build dashboards using Python and SQL.',
    skills: ['Python', 'SQL', 'Pandas', 'Tableau'],
    category: 'Data', opportunityType: 'Freelance', workMode: 'Remote',
    experienceLevel: 'Intermediate', location: 'Remote', country: 'US', city: '',
    budgetMin: 40, budgetMax: 80, stipend: null, currency: 'USD',
    duration: '2 months', applyType: 'external', applyUrl: '#',
    isVerified: false, isUrgent: false,
    postedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    deadline: null, employerRating: 4.3,
    tags: ['Python', 'SQL', 'Data', 'Remote'], isSaved: false, isApplied: false, raw: {},
  },
];
